source 'https://rubygems.org'
ruby '2.5.5'

# Please sort by alphabet!

gem 'activesupport'
gem 'appium_capybara', '~> 1.3'
gem 'browsermob-proxy', '0.3.1'
gem 'capybara', '3.18.0'
gem 'capybara-screenshot', '~> 1.0', '>= 1.0.23'
gem 'cucumber', '~> 3.1'
gem 'danger', '~> 6.3', '>= 6.3.2'
gem 'danger-gitlab'
gem 'dotenv', '~> 2.7.5'
gem 'faker', :git => 'https://github.com/stympy/faker.git', :branch => 'master'
gem 'faraday', '0.17.3'
gem 'filesize', '~> 0.2.0'
gem 'geckodriver-helper', '~> 0.0.5'
gem 'googleauth', '0.11.0'
gem 'headless', '~> 2.3', '>= 2.3.1'
gem 'httparty', '0.17.0'
gem 'json', '1.8.5'
gem 'jsonpath', '~> 0.8.7'
gem 'json_matchers', '~> 0.11.1'
gem 'json_schema', '~> 0.20.8'
gem 'jwt','2.2.1'
gem 'multipart-post'
gem 'mysql2', '~> 0.5.2'
gem 'net-scp', '~> 2.0'
gem 'net-ssh', '~> 5.2'
gem 'nokogiri', '~> 1.7', '>= 1.7.0.1'
gem 'parallel_tests', group: %i[development test]
gem 'pry', '~> 0.10.4'
gem 'rake', '~> 12.3.3'
gem 'report_builder'
gem 'rotp', '5.1.0'
gem 'rspec', '~> 3.8.0'
gem 'rspec-retry', '~> 0.4.5'
gem 'selenium-webdriver', '~> 3.142', '>= 3.142.4'
gem 'slack-incoming-webhooks', '0.3.0'
gem 'sinatra', '1.3.1'
gem 'site_prism', '~> 3.4.1'
gem 'telegramAPI', '~> 1.4', '>= 1.4.2'
gem 'wannabe_bool', '~> 0.7.1'
gem 'webdrivers', '~> 4.0'
gem 'xvfb', '1.0.4'

# Pronto
gem 'pronto'
gem 'pronto-flay', require: false
gem 'pronto-reek', require: false
gem 'pronto-rubocop', require: false
